### ISSUE TITLE
请问为什么会报不存在错误

### ISSUE THREAD

**Issue by GuanJdoJ** [ant-design/pro-blocks#54]
E:\code\web\learn\my-ant-design-pro
λ npx umi block add ant-design-pro/Monitor --path /dashboard/monitor --js
√ 😁  Parse url and args
√ 🚒 Git fetch
√ 🚪 Git checkout master
√ 🚀 Git pull
×  error     AssertionError [ERR_ASSERTION]: C:\Users\gj \ .umi\blocks\github.com\ant-design\pro-blocks\ant-design-pro \Monitor don't exists
    at E:\code\web\learn\my-ant-design-pro\node_modules\umi-build-dev\lib\plugins\commands\block\index.js:145:27
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (E:\code\web\learn\my-ant-design-pro\node_modules\umi-build-dev\lib\plugins\commands\block\index.js:42:103)
    at _next (E:\code\web\learn\my-ant-design-pro\node_modules\umi-build-dev\lib\plugins\commands\block\index.js:44:194)
    at process._tickCallback (internal/process/next_tick.js:68:7)

这是啥原因

**Comment by GuanJdoJ** [comment]
知道了，照着文档的block url写错了，应该到预览页面去复制。文档写的是这个“npx umi block add ant-design-pro/Monitor --path /dashboard/monitor --js”，正确的应该是“npx umi block add DashboardMonitor --path=/dashboard/monitor --js”，

**Comment by xiaohuoni** [comment]
@GuanJdoJ 哪个文档？

**Comment by GuanJdoJ** [comment]
> @GuanJdoJ 哪个文档？

https://pro.ant.design/docs/block-cn
