### ISSUE TITLE
window7 npm run fetch:blocks无法下载

### ISSUE THREAD

**Issue by wangdejian163** [ant-design/pro-blocks#91]
卡在半路就不动了，一次报错。一次就到eception/500就停了。

**Comment by zwh** [comment]
我也发现了这个issue，我的平台是windows 10. 当我切换到Mac OS后，按照文档说明，npm run fetch:blocks 一条命令就搞定了。虽然我可以用mac，但是还是希望windows 平台下的bug得到修复。
非常感谢。

**Comment by zwh** [comment]
`C:\Dev\AntDesign>npm run fetch:blocks

> ant-design-pro@1.0.0 fetch:blocks C:\Dev\AntDesign
> pro fetch-blocks && npm run prettier


C:\Dev\AntDesign>"node"  "C:\Dev\AntDesign\node_modules\.bin\\..\_@ant-design_pro-cli@1.0.14@@ant-design\pro-cli\cli.js" fetch-blocks
√ �  find config.ts ...
√ �  install login  to: /user/login
√ �  install register  to: /user/register
√ �  install register.result  to: /user/register-result
√ �  install analysis  to: /dashboard/analysis
√ �  install monitor  to: /dashboard/monitor
√ �  install workplace  to: /dashboard/workplace
√ �  install basicform  to: /form/basic-form
√ �  install stepform  to: /form/step-form
√ �  install advancedform  to: /form/advanced-form
√ �  install searchtable  to: /list/table-list
√ �  install basiclist  to: /list/basic-list
√ �  install cardlist  to: /list/card-list
√ �  install search-list  to: /list/search
√ �  install articles  to: /list/search/articles
√ �  install projects  to: /list/search/projects
√ �  install applications  to: /list/search/applications
√ �  install basic  to: /profile/basic
√ �  install advanced  to: /profile/advanced
√ �  install success  to: /result/success
√ �  install fail  to: /result/fail
√ �  install not-permission  to: /exception/403
√ �  install not-find  to: /exception/404
√ �  install server-error  to: /exception/500
√ �  install center  to: /account/center
√ �  install settings  to: /account/settings
√ �  install flow  to: /editor/flow
√ �  install mind  to: /editor/mind
√ �  install koni  to: /editor/koni
√ �  insert BasicLayout success
√ �  insert RightContent success
√ �  insert blankLayoutPath success
npm install --registry=https://registry.npm.taobao.org
- �  install dependencies package(node:26724) UnhandledPromiseRejectionWarning: Error: Command failed with exit code 1: npm install --registry=https://registry.npm.taobao.org
    at makeError (C:\Dev\AntDesign\node_modules\_execa@3.3.0@execa\lib\error.js:56:11)
    at Function.module.exports.sync (C:\Dev\AntDesign\node_modules\_execa@3.3.0@execa\index.js:188:17)
    at Function.module.exports.commandSync (C:\Dev\AntDesign\node_modules\_execa@3.3.0@execa\index.js:227:15)
    at execCmd (C:\Dev\AntDesign\node_modules\_@ant-design_pro-cli@1.0.14@@ant-design\pro-cli\src\fetch-blocks\index.js:72:16)
    at module.exports (C:\Dev\AntDesign\node_modules\_@ant-design_pro-cli@1.0.14@@ant-design\pro-cli\src\fetch-blocks\index.js:180:3)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:26724) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a
promise which was not handled with .catch(). (rejection id: 1)
(node:26724) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a n
on-zero exit code.
\ �  install dependencies package(node:26724) UnhandledPromiseRejectionWarning: FetchError: request to https://registry.npmjs.org/ failed, reason: Client network socket disconnected bef
ore secure TLS connection was established
    at ClientRequest.<anonymous> (C:\Dev\AntDesign\node_modules\_node-fetch@2.6.0@node-fetch\lib\index.js:1455:11)
    at ClientRequest.emit (events.js:210:5)
    at TLSSocket.socketErrorListener (_http_client.js:406:9)
    at TLSSocket.emit (events.js:210:5)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
(node:26724) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a
promise which was not handled with .catch(). (rejection id: 2)
\ �  install dependencies packageTerminate batch job (Y/N)?
^C
`
